
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
server.port=8082
spring.datasource.druid.url=jdbc:mysql://127.0.0.1:3306/water?characterEncoding=utf-8
#49.234.25.18
spring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.druid.username=root
#lkw
spring.datasource.druid.password=148963
#123456
#??????????,???2MB??
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
#
##????
#spring.security.user.name=root
#spring.security.user.password=123456
#

mybatis-plus.global-config.db-config.id-type: ASSIGN_UUID


#MQTT-服务端地址
mqtt.host=ws://127.0.0.1:8083/mqtt
#服务器的地址
#MQTT-服务端用户名
#mqtt.username=admin
#MQTT-服务端密码
#mqtt.password=public
#MQTT-是否清理session
mqtt.cleansession=false
#MQTT-当前客户端的唯一标识
mqtt.clientid=MQTT-Water
#当前客户端的默认主题
mqtt.default_topic=water/sensor
#发送超时时间
mqtt.timeout=1000
#心跳时间
mqtt.keepalive = 10
#连接超时时间
mqtt.connectionTimeout=3000
